# Generated by Django 4.2.24 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='unit',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='sentence_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('transferred', 'Trasladado'), ('released', 'Liberado')], default='active', max_length=20),
        ),
    ]
