# Generated by Django 4.2.24 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dni',
            field=models.CharField(max_length=20, unique=True, null=True, blank=True),
        ),
    ]
