# Generated by Django 4.2.24 on 2026-01-30

from django.db import migrations, models


def fill_fake_dni(apps, schema_editor):
    Person = apps.get_model('api', 'Person')
    for person in Person.objects.filter(dni__isnull=True).iterator():
        person.dni = f"FAKE-{person.id:06d}"
        person.save(update_fields=['dni'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_dni'),
    ]

    operations = [
        migrations.RunPython(fill_fake_dni, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
