# Generated by Django 4.2.24 on 2026-01-30

from django.db import migrations


def update_dni_format(apps, schema_editor):
    Person = apps.get_model('api', 'Person')
    qs = Person.objects.filter(dni__isnull=True) | Person.objects.filter(dni__startswith='FAKE-')
    for person in qs.iterator():
        person.dni = str(person.id).zfill(8)
        person.save(update_fields=['dni'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fill_dni_and_require'),
    ]

    operations = [
        migrations.RunPython(update_dni_format, migrations.RunPython.noop),
    ]
