# Generated by Django 4.2.24 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_fake_dni_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='legajo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
