# Generated by Django 4.2.24 on 2026-01-30

from django.db import migrations, models


def fill_fake_legajo(apps, schema_editor):
    Person = apps.get_model('api', 'Person')
    for person in Person.objects.filter(legajo__isnull=True).iterator():
        person.legajo = f"LEG-{person.id:06d}"
        person.save(update_fields=['legajo'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_person_legajo'),
    ]

    operations = [
        migrations.RunPython(fill_fake_legajo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='person',
            name='legajo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
